export interface Destination {
  id: string;
  name: string;
  title: string;
  description: string;
  highlights: string[];
  ideal_for: string[];
  best_for: string[];
  image: string;
  images: string[];
  region: "Kashmir" | "Ladakh";
  featured?: boolean;
  slug: string;
}

export const destinations: Destination[] = [
  // ── Featured 6 (used on homepage bento grid) ─────────────────────────
  {
    id: "dest_001",
    name: "Srinagar",
    title: "The Heart of Kashmir",
    description: "Famous for Dal Lake, houseboats, Mughal gardens, and traditional Kashmiri culture.",
    highlights: ["Dal Lake", "Houseboats", "Shikara Ride", "Mughal Gardens"],
    ideal_for: ["Couples", "Families", "First-time visitors"],
    best_for: ["Sightseeing", "Culture", "Relaxation"],
    image: "/images/kashmir-dal-lake-bg.jpg",
    images: ["/images/kashmir-dal-lake-bg.jpg", "/images/srinagar-city.jpg", "/images/mughal-gardens.jpg", "/images/nigeen-lake.jpg", "/images/hazratbal-shrine.jpg", "/images/shankracharya-temple.jpg", "/images/parimahal.jpg"],
    region: "Kashmir",
    featured: true,
    slug: "srinagar",
  },
  {
    id: "dest_002",
    name: "Gulmarg",
    title: "Meadow of Flowers",
    description: "A top destination for snow, skiing, and the famous Gondola ride offering panoramic Himalayan views.",
    highlights: ["Gondola Ride", "Snow Sports", "Skiing", "Meadows"],
    ideal_for: ["Adventure lovers", "Couples", "Snow seekers"],
    best_for: ["Winter trips", "Adventure", "Photography"],
    image: "/images/gulmarg.jpg",
    images: ["/images/gulmarg.jpg", "/images/razdan-pass.jpg", "/images/sinthan-top.webp", "/images/kaksang-la.webp"],
    region: "Kashmir",
    featured: true,
    slug: "gulmarg",
  },
  {
    id: "dest_003",
    name: "Pahalgam",
    title: "Valley of Shepherds",
    description: "A scenic valley known for rivers, pine forests, and the beautiful Aru and Betaab valleys.",
    highlights: ["Lidder River", "Betaab Valley", "Aru Valley"],
    ideal_for: ["Families", "Nature lovers", "Honeymooners"],
    best_for: ["Relaxation", "Nature", "Scenic stays"],
    image: "/images/pahalgam.jpg",
    images: ["/images/pahalgam.jpg", "/images/aruvillage.jpg", "/images/verinag.jpg", "/images/aharbal-waterfall.webp", "/images/daksum.jpg"],
    region: "Kashmir",
    featured: true,
    slug: "pahalgam",
  },
  {
    id: "dest_004",
    name: "Sonamarg",
    title: "Meadow of Gold",
    description: "Known for glaciers, alpine landscapes, and breathtaking mountain views along the Sindh River.",
    highlights: ["Thajiwas Glacier", "High-altitude drives", "Snow views"],
    ideal_for: ["Adventure travelers", "Nature lovers"],
    best_for: ["Glacier visits", "Road trips", "Summer travel"],
    image: "/images/sonamarg.jpg",
    images: ["/images/sonamarg.jpg", "/images/gurez-habba-khatoon.jpg", "/images/uming-la.jpg", "/images/zanskar-valley.jpg"],
    region: "Kashmir",
    featured: true,
    slug: "sonamarg",
  },
  {
    id: "dest_005",
    name: "Doodhpathri",
    title: "Valley of Milk",
    description: "A peaceful meadow with lush greenery and flowing streams — far from the tourist crowds.",
    highlights: ["Green meadows", "Streams", "Picnic spots"],
    ideal_for: ["Families", "Day trips", "Nature lovers"],
    best_for: ["Relaxation", "Short trips"],
    image: "/images/doodhpathri.jpg",
    images: ["/images/doodhpathri.jpg", "/images/bungus-valley.webp", "/images/wular-lake.jpg", "/images/dachigan-national-park.jpg"],
    region: "Kashmir",
    featured: true,
    slug: "doodhpathri",
  },
  {
    id: "dest_006",
    name: "Yusmarg",
    title: "Hidden Gem of Kashmir",
    description: "A quiet and less crowded destination with scenic pine forests and open meadows.",
    highlights: ["Pine forests", "Open meadows", "Peaceful environment"],
    ideal_for: ["Couples", "Offbeat travelers"],
    best_for: ["Peace", "Nature walks"],
    image: "/images/yousmarg.jpg",
    images: ["/images/yousmarg.jpg", "/images/lamayuru.jpg", "/images/tso-moriri-lake.jpg", "/images/leh-ladakh.jpg", "/images/khardungla-pass.png"],
    region: "Kashmir",
    featured: true,
    slug: "yusmarg",
  },

  // ── Additional Kashmir Destinations ──────────────────────────────────
  {
    id: "dest_007",
    name: "Gurez Valley",
    title: "Land of Habba Khatoon",
    description: "A remote and pristine valley near the Line of Control, famous for its wooden houses and Habba Khatoon Peak.",
    highlights: ["Habba Khatoon Peak", "Kishanganga River", "Tribal Culture"],
    ideal_for: ["Offbeat travelers", "Trekkers"],
    best_for: ["Adventure", "Photography", "Isolation"],
    image: "/images/gurez-habba-khatoon.jpg",
    images: ["/images/gurez-habba-khatoon.jpg", "/images/bungus-valley.webp"],
    region: "Kashmir",
    slug: "gurez-valley",
  },
  {
    id: "dest_008",
    name: "Razdan Pass",
    title: "Gateway to Gurez",
    description: "A high-altitude mountain pass at 3,300m connecting Bandipora to Gurez with sweeping valley views.",
    highlights: ["Altitude views", "Mountain passes", "Snow in winter"],
    ideal_for: ["Adventure travelers", "Photographers"],
    best_for: ["Road trips", "Photography"],
    image: "/images/razdan-pass.jpg",
    images: ["/images/razdan-pass.jpg", "/images/sinthan-top.webp"],
    region: "Kashmir",
    slug: "razdan-pass",
  },
  {
    id: "dest_009",
    name: "Sinthan Top",
    title: "Roof of Kashmir",
    description: "A scenic mountain pass at 3,748m offering stunning views of the Himalayan ranges and surrounding meadows.",
    highlights: ["Panoramic views", "Snow meadows", "Alpine flowers"],
    ideal_for: ["Trekkers", "Nature lovers"],
    best_for: ["Photography", "Trekking", "Summer escape"],
    image: "/images/sinthan-top.webp",
    images: ["/images/sinthan-top.webp", "/images/razdan-pass.jpg"],
    region: "Kashmir",
    slug: "sinthan-top",
  },
  {
    id: "dest_010",
    name: "Dachigam National Park",
    title: "Sanctuary of the Hangul",
    description: "Home to the rare Kashmir Stag (Hangul) and located just 22 km from Srinagar city.",
    highlights: ["Hangul Deer", "Leopards", "Bird Watching"],
    ideal_for: ["Wildlife lovers", "Families"],
    best_for: ["Wildlife safaris", "Nature walks"],
    image: "/images/dachigan-national-park.jpg",
    images: ["/images/dachigan-national-park.jpg", "/images/wular-lake.jpg"],
    region: "Kashmir",
    slug: "dachigam-national-park",
  },
  {
    id: "dest_011",
    name: "Daksum",
    title: "Forest Retreat",
    description: "A serene forest destination in Anantnag known for its dense coniferous forests and trout streams.",
    highlights: ["Pine forests", "Trout streams", "Serene atmosphere"],
    ideal_for: ["Nature lovers", "Couples"],
    best_for: ["Camping", "Fishing", "Relaxation"],
    image: "/images/daksum.jpg",
    images: ["/images/daksum.jpg", "/images/aharbal-waterfall.webp", "/images/verinag.jpg"],
    region: "Kashmir",
    slug: "daksum",
  },
  {
    id: "dest_012",
    name: "Aharbal Waterfall",
    title: "Niagara of Kashmir",
    description: "A majestic waterfall on the Vishav River, surrounded by dense forests and picturesque meadows.",
    highlights: ["Waterfall", "Pine forests", "Picnic spots"],
    ideal_for: ["Families", "Nature lovers"],
    best_for: ["Day trips", "Photography"],
    image: "/images/aharbal-waterfall.webp",
    images: ["/images/aharbal-waterfall.webp", "/images/daksum.jpg"],
    region: "Kashmir",
    slug: "aharbal-waterfall",
  },
  {
    id: "dest_013",
    name: "Verinag",
    title: "Spring of the Emperors",
    description: "An octagonal spring built by Emperor Jahangir, considered the source of the Jhelum River.",
    highlights: ["Mughal Spring", "Jhelum Source", "Historical garden"],
    ideal_for: ["History buffs", "Families"],
    best_for: ["Heritage tours", "Day trips"],
    image: "/images/verinag.jpg",
    images: ["/images/verinag.jpg", "/images/mughal-gardens.jpg"],
    region: "Kashmir",
    slug: "verinag",
  },
  {
    id: "dest_014",
    name: "Wular Lake",
    title: "Asia's Largest Freshwater Lake",
    description: "One of Asia's largest freshwater lakes, a crucial wetland teeming with migratory birds and fish.",
    highlights: ["Migratory birds", "Fishing", "Boating"],
    ideal_for: ["Nature lovers", "Bird watchers"],
    best_for: ["Bird watching", "Photography", "Boat rides"],
    image: "/images/wular-lake.jpg",
    images: ["/images/wular-lake.jpg", "/images/nigeen-lake.jpg"],
    region: "Kashmir",
    slug: "wular-lake",
  },
  {
    id: "dest_015",
    name: "Bungus Valley",
    title: "The Unexplored Paradise",
    description: "A little-known alpine valley near Kupwara with vast meadows, dense forests and glacial streams.",
    highlights: ["Alpine meadows", "Dense forests", "Glacial streams"],
    ideal_for: ["Trekkers", "Offbeat travelers"],
    best_for: ["Trekking", "Camping", "Adventure"],
    image: "/images/bungus-valley.webp",
    images: ["/images/bungus-valley.webp", "/images/gurez-habba-khatoon.jpg"],
    region: "Kashmir",
    slug: "bungus-valley",
  },
  {
    id: "dest_016",
    name: "Aru Village",
    title: "Gateway to Kolahoi Glacier",
    description: "A charming village near Pahalgam serving as the base camp for treks to Kolahoi Glacier and Tarsar Lake.",
    highlights: ["Kolahoi Glacier trek", "Tarsar Lake", "Alpine meadows"],
    ideal_for: ["Trekkers", "Adventure seekers"],
    best_for: ["Trekking", "Camping", "Photography"],
    image: "/images/aruvillage.jpg",
    images: ["/images/aruvillage.jpg", "/images/pahalgam.jpg"],
    region: "Kashmir",
    slug: "aru-village",
  },
  {
    id: "dest_017",
    name: "Nigeen Lake",
    title: "Jewel in the Ring",
    description: "A quieter and cleaner lake adjoining Dal Lake, perfect for peaceful houseboat stays away from crowds.",
    highlights: ["Houseboats", "Lotus gardens", "Tranquil waters"],
    ideal_for: ["Couples", "Honeymooners"],
    best_for: ["Relaxation", "Photography", "Romantic stays"],
    image: "/images/nigeen-lake.jpg",
    images: ["/images/nigeen-lake.jpg", "/images/kashmir-dal-lake-bg.jpg"],
    region: "Kashmir",
    slug: "nigeen-lake",
  },
  {
    id: "dest_018",
    name: "Hazratbal Shrine",
    title: "The Sacred Shrine",
    description: "A revered Muslim shrine on the shores of Dal Lake, housing a relic of the Prophet Muhammad.",
    highlights: ["Sacred relic", "Dal Lake views", "Marble architecture"],
    ideal_for: ["Pilgrims", "Culture seekers"],
    best_for: ["Spiritual visits", "Heritage tours"],
    image: "/images/hazratbal-shrine.jpg",
    images: ["/images/hazratbal-shrine.jpg", "/images/kashmir-dal-lake-bg.jpg"],
    region: "Kashmir",
    slug: "hazratbal-shrine",
  },
  {
    id: "dest_019",
    name: "Shankaracharya Temple",
    title: "Temple on the Hill",
    description: "An ancient Hindu temple dedicated to Lord Shiva, perched atop the Shankaracharya Hill at 1,000 feet.",
    highlights: ["Hilltop views", "Ancient temple", "City panorama"],
    ideal_for: ["Pilgrims", "History buffs"],
    best_for: ["Spiritual visits", "Panoramic views"],
    image: "/images/shankracharya-temple.jpg",
    images: ["/images/shankracharya-temple.jpg", "/images/srinagar-city.jpg"],
    region: "Kashmir",
    slug: "shankaracharya-temple",
  },
  {
    id: "dest_020",
    name: "Mughal Gardens",
    title: "Gardens of Paradise",
    description: "A trio of stunning Mughal-era terraced gardens — Shalimar, Nishat, and Chashme Shahi — overlooking Dal Lake.",
    highlights: ["Shalimar Bagh", "Nishat Bagh", "Chashme Shahi"],
    ideal_for: ["Families", "History buffs", "Couples"],
    best_for: ["Heritage tours", "Photography", "Picnics"],
    image: "/images/mughal-gardens.jpg",
    images: ["/images/mughal-gardens.jpg", "/images/parimahal.jpg", "/images/kashmir-dal-lake-bg.jpg"],
    region: "Kashmir",
    slug: "mughal-gardens",
  },
  {
    id: "dest_021",
    name: "Parimahal",
    title: "Palace of the Fairies",
    description: "A 17th-century terraced garden and palace ruin in Srinagar offering breathtaking views of Dal Lake.",
    highlights: ["Terraced gardens", "Dal Lake views", "Mughal history"],
    ideal_for: ["History buffs", "Photographers"],
    best_for: ["Heritage tours", "Sunset views"],
    image: "/images/parimahal.jpg",
    images: ["/images/parimahal.jpg", "/images/mughal-gardens.jpg"],
    region: "Kashmir",
    slug: "parimahal",
  },
  {
    id: "dest_022",
    name: "Srinagar City",
    title: "City of Lakes",
    description: "The summer capital of Jammu & Kashmir — a city of lakes, shikaras, wooden mosques and vibrant bazaars.",
    highlights: ["Old City", "Lal Chowk", "Jama Masjid", "Shikara rides"],
    ideal_for: ["First-time visitors", "Food lovers", "Shopaholics"],
    best_for: ["City tours", "Shopping", "Culture"],
    image: "/images/srinagar-city.jpg",
    images: ["/images/srinagar-city.jpg", "/images/kashmir-dal-lake-bg.jpg", "/images/hazratbal-shrine.jpg"],
    region: "Kashmir",
    slug: "srinagar-city",
  },

  // ── Ladakh Destinations ───────────────────────────────────────────────
  {
    id: "dest_023",
    name: "Leh Ladakh",
    title: "Land of High Passes",
    description: "A high-altitude desert plateau dotted with ancient monasteries, turquoise lakes and rugged mountain passes.",
    highlights: ["Monasteries", "Pangong Lake", "Magnetic Hill"],
    ideal_for: ["Adventure seekers", "Bikers", "Photographers"],
    best_for: ["Road trips", "Trekking", "Spirituality"],
    image: "/images/leh-ladakh.jpg",
    images: ["/images/leh-ladakh.jpg", "/images/lamayuru.jpg", "/images/khardungla-pass.png"],
    region: "Ladakh",
    slug: "leh-ladakh",
  },
  {
    id: "dest_024",
    name: "Lamayuru",
    title: "Moonland of Ladakh",
    description: "A surreal moon-like landscape featuring one of Ladakh's oldest Buddhist monasteries perched on dramatic cliffs.",
    highlights: ["Lamayuru Monastery", "Moonland landscape", "Ancient murals"],
    ideal_for: ["Photographers", "Culture seekers", "Trekkers"],
    best_for: ["Photography", "Buddhist heritage", "Road trips"],
    image: "/images/lamayuru.jpg",
    images: ["/images/lamayuru.jpg", "/images/leh-ladakh.jpg"],
    region: "Ladakh",
    slug: "lamayuru",
  },
  {
    id: "dest_025",
    name: "Tso Moriri Lake",
    title: "Mountain Lake of Ladakh",
    description: "A pristine high-altitude lake at 4,522m, home to rare bar-headed geese and Tibetan wild asses.",
    highlights: ["Wildlife", "Pristine waters", "Nomadic culture"],
    ideal_for: ["Wildlife lovers", "Photographers", "Trekkers"],
    best_for: ["Photography", "Wildlife spotting", "Camping"],
    image: "/images/tso-moriri-lake.jpg",
    images: ["/images/tso-moriri-lake.jpg", "/images/leh-ladakh.jpg"],
    region: "Ladakh",
    slug: "tso-moriri-lake",
  },
  {
    id: "dest_026",
    name: "Khardungla Pass",
    title: "Top of the World",
    description: "One of the world's highest motorable passes at 5,359m, offering jaw-dropping views of the Karakoram ranges.",
    highlights: ["World's highest pass", "Karakoram views", "Bike expeditions"],
    ideal_for: ["Bikers", "Adventure seekers"],
    best_for: ["Bike trips", "Photography", "Adventure"],
    image: "/images/khardungla-pass.png",
    images: ["/images/khardungla-pass.png", "/images/leh-ladakh.jpg", "/images/uming-la.jpg"],
    region: "Ladakh",
    slug: "khardungla-pass",
  },
  {
    id: "dest_027",
    name: "Kaksang La",
    title: "High Altitude Pass",
    description: "A remote high-altitude pass in Ladakh's Zanskar region offering spectacular views of the Himalayan ranges.",
    highlights: ["Remote trekking", "Himalayan views", "Alpine terrain"],
    ideal_for: ["Trekkers", "Adventure seekers"],
    best_for: ["Trekking", "Photography"],
    image: "/images/kaksang-la.webp",
    images: ["/images/kaksang-la.webp", "/images/zanskar-valley.jpg"],
    region: "Ladakh",
    slug: "kaksang-la",
  },
  {
    id: "dest_028",
    name: "Uming La",
    title: "Remote High Pass",
    description: "A less-travelled high-altitude pass offering an untouched wilderness experience in the heart of Ladakh.",
    highlights: ["Remote terrain", "High altitude", "Pristine wilderness"],
    ideal_for: ["Trekkers", "Offbeat travelers"],
    best_for: ["Trekking", "Isolation", "Photography"],
    image: "/images/uming-la.jpg",
    images: ["/images/uming-la.jpg", "/images/kaksang-la.webp"],
    region: "Ladakh",
    slug: "uming-la",
  },
  {
    id: "dest_029",
    name: "Zanskar Valley",
    title: "Valley of White Copper",
    description: "One of Ladakh's most remote valleys, famous for the frozen Chadar river trek and dramatic gorges.",
    highlights: ["Chadar Trek", "Zanskar River", "Ancient monasteries"],
    ideal_for: ["Trekkers", "Adventure seekers"],
    best_for: ["Trekking", "Winter adventures", "Photography"],
    image: "/images/zanskar-valley.jpg",
    images: ["/images/zanskar-valley.jpg", "/images/tso-moriri-lake.jpg", "/images/lamayuru.jpg"],
    region: "Ladakh",
    slug: "zanskar-valley",
  },
];
